In [2]:
import numpy as np

In [51]:
timesteps = 10        # 100
input_features = 3    # 32
output_features = 6   # 64

In [67]:
inputs = np.random.random((timesteps, input_features))
print(type(inputs))
print(inputs)

<class 'numpy.ndarray'>
[[0.73740258 0.57764504 0.83306046]
 [0.03626558 0.23873897 0.49877685]
 [0.61819564 0.57388187 0.94520828]
 [0.10259348 0.16156474 0.75906861]
 [0.92008034 0.87984818 0.50340698]
 [0.55403127 0.3687017  0.50839407]
 [0.80450141 0.90480306 0.29829378]
 [0.92455662 0.84655065 0.45620929]
 [0.66270914 0.92850523 0.51032613]
 [0.07904602 0.83970493 0.98167777]]


In [68]:
state_t = np.zeros((output_features, ))
print(type(state_t))
print(state_t)

<class 'numpy.ndarray'>
[0. 0. 0. 0. 0. 0.]


In [69]:
W = np.random.random((output_features, input_features))
print(type(W))
print(W)

<class 'numpy.ndarray'>
[[0.30598126 0.20508644 0.09699999]
 [0.94860541 0.46390353 0.86426652]
 [0.94311292 0.09418422 0.8526629 ]
 [0.99174071 0.23145463 0.94151674]
 [0.04670376 0.31707061 0.28041799]
 [0.97038905 0.41848081 0.99503032]]


In [70]:
U = np.random.random((output_features, output_features))
print(type(U))
print(U)

<class 'numpy.ndarray'>
[[0.0021582  0.42926472 0.87593361 0.68615854 0.73757481 0.99901775]
 [0.30699128 0.5222576  0.61383427 0.92834403 0.38116067 0.95393218]
 [0.5227558  0.45146775 0.52730023 0.62493261 0.41673198 0.93631019]
 [0.83186121 0.3787075  0.49669063 0.50126798 0.62031916 0.81706113]
 [0.67940979 0.98683705 0.26381917 0.2170616  0.33401843 0.71431132]
 [0.22079161 0.87194414 0.37590082 0.92167462 0.95906531 0.52277486]]


In [71]:
b = np.random.random((output_features, ))
print(b)

[0.30988444 0.20714551 0.33519341 0.2470272  0.976738   0.35579589]


In [72]:
successive_outputs = []
print(type(successive_outputs))
print(successive_outputs)

<class 'list'>
[]


In [73]:
print(W)
print(inputs[0])
np.dot(W, inputs[0])

[[0.30598126 0.20508644 0.09699999]
 [0.94860541 0.46390353 0.86426652]
 [0.94311292 0.09418422 0.8526629 ]
 [0.99174071 0.23145463 0.94151674]
 [0.04670376 0.31707061 0.28041799]
 [0.97038905 0.41848081 0.99503032]]
[0.73740258 0.57764504 0.83306046]


array([0.42490539, 1.68746191, 1.46017869, 1.64935114, 0.45119887,
       1.78622117])

In [74]:
print(U)
print(state_t)
np.dot(U, state_t)

[[0.0021582  0.42926472 0.87593361 0.68615854 0.73757481 0.99901775]
 [0.30699128 0.5222576  0.61383427 0.92834403 0.38116067 0.95393218]
 [0.5227558  0.45146775 0.52730023 0.62493261 0.41673198 0.93631019]
 [0.83186121 0.3787075  0.49669063 0.50126798 0.62031916 0.81706113]
 [0.67940979 0.98683705 0.26381917 0.2170616  0.33401843 0.71431132]
 [0.22079161 0.87194414 0.37590082 0.92167462 0.95906531 0.52277486]]
[0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0.])

In [75]:
print(inputs)
for input_t in inputs:
    print('--------------------------------------------------------------')
    print('input_t=' + str(input_t))
    print('state=' + str(state_t))
    print('~~~~~~~~~')
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    print('np.dot(W, input_t):')
    print(np.dot(W, input_t))
    print('~~~~~~~~~')
    print('np.dot(U, state_t):')
    print(np.dot(U, state_t))
    print('~~~~~~~~~')
    print('output_t=' + str(output_t))
    print('~~~~~~~~~')
    successive_outputs.append(output_t)
    print('successive_outputs' + str(successive_outputs))
    
    state_t = output_t
   

[[0.73740258 0.57764504 0.83306046]
 [0.03626558 0.23873897 0.49877685]
 [0.61819564 0.57388187 0.94520828]
 [0.10259348 0.16156474 0.75906861]
 [0.92008034 0.87984818 0.50340698]
 [0.55403127 0.3687017  0.50839407]
 [0.80450141 0.90480306 0.29829378]
 [0.92455662 0.84655065 0.45620929]
 [0.66270914 0.92850523 0.51032613]
 [0.07904602 0.83970493 0.98167777]]
--------------------------------------------------------------
input_t=[0.73740258 0.57764504 0.83306046]
state=[0. 0. 0. 0. 0. 0.]
~~~~~~~~~
np.dot(W, input_t):
[0.42490539 1.68746191 1.46017869 1.64935114 0.45119887 1.78622117]
~~~~~~~~~
np.dot(U, state_t):
[0. 0. 0. 0. 0. 0.]
~~~~~~~~~
output_t=[0.62598698 0.95577341 0.94632465 0.95592633 0.89124302 0.97280113]
~~~~~~~~~
successive_outputs[array([0.62598698, 0.95577341, 0.94632465, 0.95592633, 0.89124302,
       0.97280113])]
--------------------------------------------------------------
input_t=[0.03626558 0.23873897 0.49877685]
state=[0.62598698 0.95577341 0.94632465 0.9559263

In [76]:
final_output_sequence = np.concatenate(successive_outputs, axis=0)
print(final_output_sequence)

[0.62598698 0.95577341 0.94632465 0.95592633 0.89124302 0.97280113
 0.99924983 0.9995599  0.9992655  0.99931226 0.99934548 0.99978062
 0.99971981 0.99997161 0.99994557 0.99996833 0.99981585 0.99998787
 0.99953007 0.99984781 0.99978699 0.99984921 0.99972217 0.99993275
 0.99977677 0.99997419 0.99993838 0.99996538 0.99981145 0.99998744
 0.99965619 0.99991775 0.99986594 0.99991029 0.99973119 0.99996122
 0.99975331 0.99995526 0.99989184 0.99993671 0.99978962 0.99997686
 0.99977237 0.99997139 0.99993341 0.99996195 0.99980249 0.99998595
 0.99974439 0.99996032 0.99990204 0.99994439 0.99981361 0.99998042
 0.9996542  0.99994226 0.99986591 0.99992409 0.99984012 0.99997437]
